### ISSUE TITLE
I have nothing to say for myself

### ISSUE THREAD

**Issue by orf53975** [GreatSCT/GreatSCT#1]
File "gr8sct.py", line 133
    self.multipleApplicable = {**self.multipleApplicable, **tempDict} #...I have nothing to say for myself
                                ^
SyntaxError: invalid syntax

**Comment by ConsciousHacker** [comment]
This bug has been fixed in the "develop" branch. This bug fix will be merged into the master branch soon. To use the develop branch, type the following commands:

`git clone https://github.com/GreatSCT/GreatSCT`
`git checkout develop`
`git pull`
