### ISSUE TITLE
dll problem

### ISSUE THREAD

**Issue by Phoenix1112** [GreatSCT/GreatSCT#10]
hello. this is great program..thanks for everything.I have a problem but it is not related to your program.
I am creating a dll file with this method >>> "regsvcs/meterpreter/rev_tcp.py"
I get a dll file and a .cs file with the above method.I want to make some changes on the .cs file.

for example, I am change function names ..i am converting .cs file to .dll file with visual studio prompt .
with this command, i am convert cs file to dll format >> csc /target:library /out:MyMaths.dll payload.cs 

but i also get error when i want to run dll file with regsvcs.exe  
this error
"1: 'C:\Users\Cyberthereaper\Desktop\MyMaths.dll' 'has no descriptive name

how to fix this problem?

other method
I'm opening a cs file with visual studio 2017 ..i am added reference "System.EnterpriseServices" and "System.Windows.Forms" .. i did compile payload.cs file with class libary ..

but i also get error when i want to run dll file with regsvcs.exe  
Invalid classes derived from "servicedcomponent" ..Classes must be public and concrete, must be public default builders, and must meet all other ComVisibility requirements
lIUPQhMj.NfyxwnnZjTe: Unspecified error

what is problem ? how you converting .cs file to dll ?

**Comment by ConsciousHacker** [comment]
Closing this issue as it's not related to this project, look at the source code to understand how GreatSCT compiles this payload
