### ISSUE TITLE
生成失败问题，第26个payload

### ISSUE THREAD

**Issue by Gumihx** [GreatSCT/GreatSCT#11]

**Comment by Gumihx** [comment]
![QQ截图20191229203534](https://user-images.githubusercontent.com/49981027/71557013-0d421500-2a7b-11ea-88b3-eb9416a9dd11.jpg)

**Comment by TommyWhite** [comment]
Same issue for me, also found out that https://blog.conscioushacker.io/wine.tgz
 is not accessible during the installation.
