### ISSUE TITLE
Installation issues on latest Kali

### ISSUE THREAD

**Issue by TommyWhite** [GreatSCT/GreatSCT#13]
Hello, 

Tried several times, installation does not finish successfully.
File https://blog.conscioushacker.io/wine.tgz is not accessible anymore.
Even if I Install wine manually and comment downloading wine.tgz in config.sh.
Also after complete installation any payload generation is broken.

**Comment by helifen185** [comment]
同样遇到了这个问题

**Comment by TommyWhite** [comment]
Made it to work. The main point is -- **do installation from GUI terminal**, not SSH or pty.
