### ISSUE TITLE
Installation issue on Arch

### ISSUE THREAD

**Issue by Razack-git** [GreatSCT/GreatSCT#14]
setup.sh fail to install the depencys from base-devels ...

its a typo, correct to base-devel ([https://www.archlinux.org/groups/x86_64/base-devel/](url))

**Comment by hoodsware** [comment]
And Manjaro is missing from the installation. I use it for my CTFs and practice with my VMs. I'll be grateful if you added. I only use manjaro with blackarch repo to install the tools I need so in other words not all of them.

**Comment by ConsciousHacker** [comment]
I'm no longer maintaining this project, feel free to submit a pull request to fix this and I'll merge it in
