### ISSUE TITLE
Error starting GreatSct

### ISSUE THREAD

**Issue by darkness2020** [GreatSCT/GreatSCT#18]
When I start the tool with ./Greatsct.py it briefely displays some sysntax erros on screen but opens main menu. I chiise list, it gives me 1)Bypass, but when I choose bypass it returns to main menu. What to do ?

**Comment by xinhuang** [comment]
I had the same issue. Make sure you have python in your path and it's pointing to python3. Then re-run the setup script.

**Comment by ConsciousHacker** [comment]
I no longer actively maintain or support this project
